### PR TITLE
Remove IIIF code from Hyku, rely on Hyrax functionality

### PR DESCRIPTION
**Pull request by geekscruff**
Removes all local code and specs that duplicate IIIF functionality now in Hyrax. Also removes the universal viewer code in public/bower_includes - this now comes via hyrax from `pulibrary/pul_uv_rails`

Configures iiif support in hyrax to true.

### CODE REVIEW

**Comment by orangewolf** [comment]
@geekscruff would love @cbeer promised eyes on this, but it otherwise looks ready to me.  Is there anything else that makes this "WIP"?

**Comment by geekscruff** [comment]
@orangewolf nope, I just forgot to rename it!

**Comment by orangewolf** [comment]
fixed the fact that I @ messages the wrong Chris here earlier.

**Comment by orangewolf** [comment]
merged because Coveralls was broken, but is fixed now.

**Pull request merged**
