### PR TITLE
Fix zookeeper bundle install

### PR DESCRIPTION
**Pull request by cjcolvar**
Fixes the CircleCI build which is failing currently.  See https://app.circleci.com/pipelines/github/samvera/hyku/323/workflows/74d691c6-f883-4db9-af65-28ac6f8302aa/jobs/352

@samvera/hyku-code-reviewers

### CODE REVIEW

**Review by orangewolf — APPROVED** [review]

**Comment by cjcolvar** [comment]
@orangewolf How worried are you about the failing tests?  It looks like they passed on the rerun but the build still failed.  Do you think we could go ahead and merge this or should I restart the build until it goes green?

**Comment by orangewolf** [comment]
the failure here is coveralls - I vote we change the way coverage is done because that's been pretty flakey. do you know if its flakey on Hyku or is it just flakey everywhere?

**Comment by orangewolf** [comment]
@cjcolvar separately there is some flapping feature specs. We're working on a project right now to try and nail down what is causing those, but its super time consuming.

**Comment by cjcolvar** [comment]
@orangewolf I think Coveralls is just flakey everywhere.  I could make a PR to switch to codeclimate if that sounds good to you.

**Pull request merged**
