### PR TITLE
Iiif print demo copy

### PR DESCRIPTION
**Pull request by ShanaLMoore**
# Summary

Installed IiifPrint with basic default configurations. This work has been deployed to: https://demo.hyku-iiif.notch8.cloud/

Upgrade Bulkrax to v5.0.0 due to required dependencies for iiif_print.

# Screenshots / Video

SAMPLE FILE: [iiif-print-test.pdf](https://github.com/samvera/hyku/files/10876820/iiif-print-test.pdf)

## PDF Splitting. Importing a pdf that has multiple pages should create a child work for each page. 
image

## Parent OCR search for child data (metadata or ocr)
image

## Catalog Search for child data (metadata or ocr) should not return the child works
image

# Expected Behavior

User should be able to perform all that's listed in the [features list's user story tab](https://docs.google.com/spreadsheets/d/1V3DoknWcmGQwc5StU1zBQxpGRQ7ttctwxXpbfxJvtsw/edit#gid=882540390)

# Notes

this branch is iiif-print-demo + the [changes](https://github.com/samvera/hyku/pull/1925) to improve the solr build. 

I want to verify that the build issues are resolved with this branch/PR, before merging in the code. ✅

### CODE REVIEW

**Comment by ShanaLMoore** [comment]
The issue still exists. Solr is not creating a core. 

image

**Comment by ShanaLMoore** [comment]
> The issue still exists. Solr is not creating a core.
> 
> image

RESOLVED ✅

**Review by orangewolf — APPROVED** [review]
This looks good. we should likely note in the PR description that this also upgrade Bulkrax to 5.0, just so that fact is not lost in the release notes

**Comment by ShanaLMoore** [comment]
> This looks good. we should likely note in the PR description that this also upgrade Bulkrax to 5.0, just so that fact is not lost in the release notes

done ✅ good point

**Pull request merged**
