### PR TITLE
documentation reorg, plus new docs re. running "stable" version

### LINKED ISSUE #1920: README improvements for running locally
## Summary

Hyku v5 / `HEAD` 

A couple improvements could be made to the README to make it easier for people who are spinning the app up locally for the first time. Specifically: 

- Instructions on configuring Dory's config file to support the .test tld 
- Username and password for the HTTP basic auth that is in front of private tenants 

### Dory .test tld

Currently, the instructions for this simply link to [Dory's README](https://github.com/FreedomBen/dory#config-file), which has instructions for how to setup a default dory config file, but not for how to support the .test tld. This can be misleading 

### HTTP basic auth 

Since tenants are private by default, most people spinning the app up locally will hit this barrier. No documentation for this currently exists in the README. An explanation should be added, along with the default values for the username and password.

### LINKED ISSUE #1981: Hyku installation on local Desktop Docker
### Descriptive summary

I have started to do tests on installing Hyku in my local machine, but I cannot find the test user account so that I can do the demo testing. I used instructions on this page https://github.com/samvera/hyku  . Please assist.

Include what version of Hyku relates to this issue (0.x, 1.x, HEAD, etc.) if appropriate, and any relevant tracebacks if you're reporting a bug.

### Rationale
I'm tasked to install samvera as it is the solution identified by the library management to replace the legacy repository system for the consortium universities.

Provide the rationale or user story that describes "why" this issue should be addressed. Especially if this is a new feature or significant change to the existing implementation.

### Expected behavior
Login and be able to test how the system actually works
### Steps to reproduce the behavior

1. Do this
1. Then do this...

### Related work

Link to related tickets or prior related work here.

### LINKED ISSUE #2142: Documentation regarding versioning/upgrading/tagging
### Descriptive summary

I've been trying to get a test instance of the hyku stack running on my local machine, and there's been significant confusion over which version of the codebase I need to be running.

As a developer naive to this project, I read the "Running the stack" documentation, and assume I can `git clone` followed by `docker compose up` and be on my way.  

However, this results in running an old docker image against a fresh git repo.  It will pull the docker image tagged `:latest`, which, as of this writing, is about 1.5 months behind HEAD.  In my case, I run into a Ruby version mismatch, however this is irrelevant -- any number of things could go wrong in this scenario.

### Rationale

The spirit of the "Running the stack" documentation is to allow someone to get a test instance running quickly. Therefore some documentation is needed to clarify how to correctly match the codebase version to the docker version.

### Expected behavior

There are several possible paths to take:

1) Instruct the user to clone the latest release, possibly introducing a new `stable` tag. There will be a maintainer responsibility to keep git `stable` in sync with docker `:latest.` Also document how the user can run the bleeding-edge if they so choose, by specifying the TAG env var when running `docker compose up`.

2) Instruct the user to `docker compose build` prior to `docker compose up.` I'm not a docker expert, but it appears this would rebuild the image using the current codebase. However, this could cause confusion if the user ever `docker compose pull`, because that will pull the wrong image again.

3) Explicitly state the correct version of the image in docker-compose.yml instead of using `:latest` -- this is probably impractical and error-prone, unless it can be automated.

**EDIT:** The documentation should also cover upgrading, which will largely overlap with what I've already described.

### Actual behavior

There is no documentation to this effect.

FWIW, I'd be happy to offer a pull request, but please point me in the right direction on how the maintainers would like to handle this.

### LINKED ISSUE #2155: Docker containers unsuccessful due to old Ruby version
### Descriptive summary

I'm attempting to run the docker containers locally on my machine. I followed the directions in the readme and after running `docker compose up web` the `initialize_app` service logs in Docker Desktop showed this error, which due to the dependencies preventing the rest of the containers from spinning up.

> hyrax-5.0.0.rc2 requires ruby version >= 3.2, which is incompatible with the
> current version, 2.7.7

### Rationale

The documentation states that Ruby 2.7 is recommended, but if a later version is needed, then this and any troubleshooting steps should be addressed in documentation.

### Expected behavior

Docker containers should spin up after running `docker compose up web`

### Actual behavior

`initialize-app` docker service fails to start due to an error message about requiring ruby >=3.2

### Steps to reproduce the behavior

1. run `ruby -v` to verify your version. Mine was `3.3.0`
1. Clone the repo
1. Ensure Docker Desktop is downloaded, installed and running.
2. `cd` into the repo
3. run `gem install dory' and `dory up` then `docker compose up web`
4. As long as you don't run in detached mode, you should see the error below, and if you inspect the docker logs for the `initialize_app` service you should see the error message above.
> service "initialize_app" didn't complete successfully: exit 5` and 

### Additional info

I'd be happy to work on a first PR to fix this, but was wondering if anyone could point me in the right direction.

### PR DESCRIPTION
**Pull request by ryan-lang**
Fixes #1920
Fixes #1981
Fixes #2155
Fixes #2142

Simply reorganizes the existing README documentation for clarity purposes, which had grown to a point where it was getting difficult to follow. Also adds a canonical approach to running the latest "stable" version locally, as suggested by @jeremyf [here](https://github.com/samvera/hyku/issues/2142#issuecomment-1908654296).

I'm a complete novice with the Samvera stack, so the documentation is mostly copy-paste from the original README, but I felt this would be a good step towards fixing a persistent pain point for new users, and good scaffolding for future doc improvements.

@samvera/hyku-code-reviewers

### CODE REVIEW

**Comment by ryan-lang** [comment]
Oh, and I am aware that some/much of this info is duplicated in the Wiki, however, since Wikis don't have PRs, I felt this might be a better way forward. Possibly the Wiki could be geared more towards active development docs? Just a thought...

**Review by ShanaLMoore — CHANGES_REQUESTED** [review]
oops - I didn't mean to request changes. I meant to comment simply Thank you! 😄

**Comment by ShanaLMoore** [comment]
Moving this to DRAFT to block merge. We need the build step to pass before merging.

**Comment by ShanaLMoore** [comment]
I'm not sure what's going on with this particular PR's build so I created a new one and pulled over your changes [here](https://github.com/samvera/hyku/pull/2232)

**Pull request closed without merging**
