### PR TITLE
Adds jobs that run at Midnight everyday to expire embargos and leases

### PR DESCRIPTION
**Pull request by BertZZ**
As part of Ubiquity Press' Hyku alignment of features developed for the British Library, this PR makes use of new Hyrax Jobs I authored for  [embargo expiry](https://github.com/samvera/hyrax/blob/master/app/jobs/embargo_expiry_job.rb) and [lease expiry](https://github.com/samvera/hyrax/blob/master/app/jobs/embargo_expiry_job.rb)

Changes proposed in this pull request:
- Bump Redis version to 4 in docker-compose
- Point Hyrax at '2.x-stable' branch for now
- Add sidekiq-cron to schedule jobs
- Add jobs to auto expire embargoes and leases 

@samvera/hyku-code-reviewers

### CODE REVIEW

**Review by orangewolf — CHANGES_REQUESTED** [review]
@BertZZ and I spoke about this in slack. Great progress here, but it looks like this is missing the multi-tenant piece and needs that before its ready for final review. We also agreed to move to a non-sidekiq specific job scheduler to continue to allow users to swap out the ActiveJob backend.

**Review by orangewolf — DISMISSED** [review]

**Review by orangewolf — APPROVED** [review]

**Comment by orangewolf** [comment]
@BertZZ did a merge, please give it a final look and hit merge if you feel good about it =-)

**Comment by BertZZ** [comment]
@orangewolf Looks like Circle is unhappy about something but it seems all the relevant tests passed so I am happy if you are :smiley:

**Comment by orangewolf** [comment]
@BertZZ i agree. There is no clear reason why it’s red.

**Pull request merged**
